# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
   include:
     - master
     - develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: BuildAndTest

  jobs:

  - job: BuildAndTest

    steps:

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: 10.0.103

    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget Tooling'

    - task: NuGetCommand@2
      displayName: Restore Solution
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build Solution
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Run Tests
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'
